<?php
// This file has been auto-generated by the PubSubRouterBundle.
return [
    'oro_sync.ping' => [[], [], [], [['text', 'oro/ping']]],
    'oro_sync.data_update' => [[], [], [], [['text', 'oro/data/update']]],
    'oro_sync.maintenance' => [[], [], [], [['text', 'oro/maintenance']]],
    'oro_message_queue.message_queue_heartbeat' => [[], [], [], [['text', 'oro/message_queue_heartbeat']]],
    'oro_email.event' => [['user_id', 'organization_id'], [], ['user_id' => '\\d+', 'organization_id' => '\\d+|\\*'], [['variable', '/', '\\d+|\\*', 'organization_id'], ['variable', '/', '\\d+', 'user_id'], ['text', 'oro/email_event']]],
    'oro_user.outdated_user_page' => [[], [], [], [['text', 'oro/outdated_user_page']]],
    'oro_entity_config.attribute_import' => [['user_id', 'config_model_id'], [], ['user_id' => '\\d+', 'config_model_id' => '\\d+'], [['variable', '/', '\\d+', 'config_model_id'], ['variable', '/', '\\d+', 'user_id'], ['text', 'oro/attribute_import']]],
    'oro_imap.sync_fail' => [['user_id'], [], ['user_id' => '\\d+|\\*'], [['variable', '/', '\\d+|\\*', 'user_id'], ['text', 'oro/imap_sync_fail']]],
    'oro_reminder.remind' => [['user_id'], [], ['user_id' => '\\d+'], [['variable', '/', '\\d+', 'user_id'], ['text', 'oro/reminder_remind']]],
];